name: Lint Golang code
on:
  push:
    branches:
      - main
    paths:
      - '**.go'
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: Check final newline
        uses: qwrtln/check-final-newline@v1.0.0
